[client]

# مسیر مخفی تونل (باید دقیقا مشابه سرور باشد)
hidden_path = "/api/v4/telemetry"

# رمز عبور تونل (باید دقیقا مشابه سرور باشد)
secret = "my_super_secret_password"

# (اختیاری) تعداد کانکشن‌های باز در هر نود برای اتصال سریع‌تر
pool_size_per_node = 16

# پشتیبانی بومی از UDP: اگر yes باشد، برای تمام پورت‌های مپ شده، سوکت UDP هم باز می‌شود
accept_udp = "yes"

# لیست IPهای تمیز کلودفلر (ارتباطات به صورت مسابقه‌ای و هوشمند با سریع‌ترین IP برقرار می‌شود)
clean_ip = [
    "104.21.32.1",
    "172.67.19.1"
]

# (اختیاری) سطح لاگ‌گیری سیستم: "trace", "debug", "info", "warn", "error"
log_level = "info"

# سرورهای لوکیشن NL
[[client.remotes]]
location = "NL"
sni = [
    "sni1.example.com:443",
    "sni2.example.com:443"
]
port_mappings = [
    "sni.nl.example.com:443=127.0.0.1:443",
    "1373=1373"
]

# سرورهای لوکیشن DE
[[client.remotes]]
location = "DE"
sni = [
    "sni3.example.com:443"
]
port_mappings = [
    "sni.de.example.com:443=127.0.0.1:443"
]
