[client]
# بهترین مقادیر حرفه‌ای برای مخفی‌سازی شامل API‌های رایج تله‌متری و سینک است
hidden_path = "/api/v4/telemetry"
secret = "My_Super_Enterprise_Secret_Key_2026!"
port_mappings = [
    "1080=127.0.0.1:8443" # هدایت ترافیک پورت 1080 به بک‌اند اصلی
]
# pool_size_per_node = 5 (پیش‌فرض 5 است در صورت عدم وجود)

[[client.remotes]]
name = "node-cloudflare"
addr = "198.51.100.25:443"
sni = "www.speedtest.net"
host = "app.yourdomain.com"

[[client.remotes]]
name = "node-direct"
addr = "198.51.100.26:443"
sni = "app2.yourdomain.com"
host = "app2.yourdomain.com"
