[server]
bind_addr = "0.0.0.0:443"
secret = "My_Super_Enterprise_Secret_Key_2026!"
hidden_path = "/api/v4/telemetry"
tls_cert = "/etc/letsencrypt/live/app.yourdomain.com/fullchain.pem"
tls_key = "/etc/letsencrypt/live/app.yourdomain.com/privkey.pem"
reality_fallback_url = "https://www.ubuntu.com"
