[server]

# آدرس و پورتی که سرور روی آن گوش می‌دهد
bind_addr = "0.0.0.0:443"

# رمز عبور مشترک بین سرور و کلاینت برای احراز هویت
secret = "my_super_secret_password"

# مسیر مخفی برای درخواست‌های تونل (باید با کلاینت یکی باشد)
hidden_path = "/api/v4/telemetry"

# مسیر فایل‌های گواهینامه TLS (برای ارتباط امن H2/HTTPS)
tls_cert = "fullchain.pem"
tls_key = "privkey.pem"

# هدف استتار (Active Probing Defense) - می‌تواند سایت یا مسیر فایل محلی باشد
camouflage_target = "https://www.ubuntu.com"

# تنظیمات دریافت خودکار گواهینامه Let's Encrypt (DNS-01 Challenge)
cloudflare_api_token = "YOUR_CLOUDFLARE_API_TOKEN"

acme_domains = [
    "domain.com",
    "*.domain.com"
]

# (اختیاری) سطح لاگ‌گیری سیستم: "trace", "debug", "info", "warn", "error"
log_level = "info"

# تنظیمات مسیریابی فوق‌سریع ترافیک بر اساس دامنه (SNI Routing)
# در این بخش می‌توانید تعیین کنید که اگر کلاینت با یکی از دامنه‌های زیر به سرور متصل شد،
# ترافیک آن بدون بازگشایی رمزنگاری (Zero-Copy) مستقیماً به آی‌پی و پورت مشخص شده (مثلاً سرور Xray) هدایت شود.
# فرمت: "دامنه:پورت_ورودی=آی‌پی_مقصد:پورت_مقصد"
port_mappings = [
    "fi.SNI.COM:443=127.0.0.2:443",
    "fr.SNI.COM:443=127.0.0.2:443",
    "tr.SNI.COM:443=127.0.0.2:443",
    "de.SNI.COM:443=127.0.0.2:443",
    "nl.SNI.COM:443=127.0.0.2:443",
    "uk.SNI.COM:443=127.0.0.2:443",
]
